language: cpp
branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"
cache: ccache
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libx11-dev
    - linux-headers-$(uname -r)
install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
- mkdir -p build && cd build && cmake .. && make
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: DFAWGA5MlEqSQF0gsMTe6DZbpCJhvUS6hxIU9OTVgu9ux9RiSAtu3XHsZeC/NmuxTQSLy85EWn/HiK+TTfYZramoMHMIs2/yE93nlqobf0Y0oNcHKuJRXfDsawfWIoNcDZ/hZ0GWa26zG2LeWvjaZif3DudOaHci0iyVqcQ4TOGfQ4p09n0SxIbwj1/l+GnfIW0ItqUoU0RXS4xXQ2eAWVvwSVPB3VhR8+L7krU5R0gRgM3VLYDnk1qoVPfl0FijvD+/rdAdMsQhxqxOJlLBUnkwM21bjd/GufEIumTdTTxq06GRknelvIKSGLV8jEAh1E3LHnaCNIsrLwTIlZ/gwVac8/qx6VKJYojj7uUF0NtzH7FPwaQ4nwXxygl7hIRTaLwq1gZ84h6Dl0T50KPbe6fC0ABjnbppJHuNXIXnPgYXKGErtwBhXSqBkvyHs47VTDIpZsZjIqOFH4goTRrZCTYiyAh+DNTtFrp9Ske1rKP2y9YZs5e31M49Oi4rnWyHZHRzZbDFO+yJQDSH5wE2rQldiQsRLyX3KmrzJ5ALAhJiEmldP/zNFsD9aM4LnKSFsncaYmG+pjbPcyReeCZfKOFauQMMi/nrwBYBwT2wEoO4GSKfSV319lCtPG+LJHu9tKjww+sAbtTnpMnm4T22VtA0pxaHO+kMuLF14QNqvgo=
